### ISSUE TITLE
feat: search text in images

### ISSUE THREAD

**Issue by zhilongjia** [yurijmikhalevich/rclip#17]
I tested that searching text in images. It works, though not so good. Any idea to improve the performance of searching text in images? Thank you.

**Comment by yurijmikhalevich** [comment]
Hi @zhilongjia! :wave: 

No plans for this at the moment. But, this can be an interesting addition to the rclip in the future. If anyone else is interested in the feature, please, give this GHI a thumbs up.

**Comment by zhilongjia** [comment]
A script to do this kind of search, which is [search_txt_in_image.sh](https://gist.github.com/zhilongjia/b7a8aeeedb6fca2821ea5c46e90b162c).
