### ISSUE TITLE
feat: allow "negative" text queries

### ISSUE THREAD

**Issue by yurijmikhalevich** [yurijmikhalevich/rclip#18]
A good example of what I mean is http://image-search.0ape.com/search?q=naked%20-person.

Thanks, @ramayer for the rclip-server and the inspiration!

Requirements:
- the current interface `rclip "query"` should continue to work
- it should correctly support following examples:
`rclip "multi word query -word1 -word2"`
`rclip "query -'multi word negative'"`
`rclip 'query -"multi word negative"'` (i.e., it should work with any type of quotes)

`rclip "multi word query -word2 some other words"` should error with the suggestion to use quotes around the negative since it's unclear how to parse it

**Comment by ramayer** [comment]
I'd like to question some of the requirements around quoting.   In particular:

>>  rclip 'query -"multi word negative"' (i.e., it should work with any type of quotes)

I've been playing more with quoted phrases, and it seems quotation marks are more significant to CLIP than I first thought.

For example, it seems the CLIP embedding for:

* [awesome](http://image-search.0ape.com/search?q=awesome) 

is extremely different than the clip embedding for:

* ["awesome"](http://image-search.0ape.com/search?q=%22awesome%22) 

Guessing from those two results, I think CLIP is inferring a more sarcastic interpretation of "awesome" when it's quoted.

Combining the concepts, it seems [car +"awesome" -awesome](http://image-search.0ape.com/search?q=car%20%2B%22awesome%22%20-awesome) seems to return the most sarcastically "awesome" cars you can find; and [reversing those expressions gives nice classic cars](http://image-search.0ape.com/search?q=car%20%2Bawesome%20-%22awesome%22).   Single quotes seem to change the CLIP embeddings too, but in more subtle ways.  Such quoted expressions would be hard to express if quotes are also used for grouping the positive and negative parts of the expression.

I think it would be clearest if the additive and subtractive phrases used separate command line parameters, like:

`rclip zebra --minus="black and white" --plus="red and blue"`

That way there's no ambiguity, and one could write `rclip car --plus='"awesome"' --minus=awesome` without risk of confusion.

If you think that's a good idea, a draft of a pull request implementing the feature in that way can be found in a pull request of a draft of such an implementation in pull request #19

**Comment by yurijmikhalevich** [comment]
@ramayer, that's a good point. You are correct that it will be tricky to pass quoted expressions if we use quotes to separate subqueries. Great find. One more benefit of going with your suggestion is that it eliminates the confusion around cases like this: `rclip "multi-word query -word2 some other words"`. I love it!

I also thought about passing multiple queries like this `rclip zebra -"black and white" +"red and blue"`, but "-" makes it interpret the query as a param, and `rclip zebra \\-"black and white" +"red and blue"` and `rclip zebra "\-black and white" +"red and blue"` look ugly and unintuitive.

Let's go with your suggestion, but replace `--minus` and `--plus` with `--add` and `--sub` (these verbs better represent the action and are shorter) and allow aliases `-a`, `-s`, and `--subtract`.
