### ISSUE TITLE
`APPRUN_ERROR: Permission denied` when running on a Synology NAS with DSM 7.1.1-42962 Update 1

### ISSUE THREAD

**Issue by yurijmikhalevich** [yurijmikhalevich/rclip#30]

**Comment by provaguest** [comment]
I have the same issue on the same hardware. Any idea regarding the cause? With previous version of DSM rclip Appimage worked fine

**Comment by yurijmikhalevich** [comment]
@provaguest, I assume that the system file structure or default permissions changed with the DSM update and rclip is AppImage tries to unpack itself into either a non-existent directory or into a directory with no write/exec rights. Going to look into this.

**Comment by yurijmikhalevich** [comment]
@provaguest, fixed in rclip@v1.2.5 https://github.com/yurijmikhalevich/rclip/releases/tag/v1.2.5

**Comment by provaguest** [comment]
I confirm that with version 1.2.5 rclip is now again working on DSM.
Thank you very much for the fix and the wonderful software.

**Comment by yurijmikhalevich** [comment]
@provaguest, thank you. I am happy that you like it :)
