### ISSUE TITLE
FasterViT?

### ISSUE THREAD

**Issue by walking-octopus** [yurijmikhalevich/rclip#37]
In the recent ML news, I noticed mentions of FasterViT, a new model with some architecture changes that is said to outperform others in the performance to accuracy ratio. I immediately wondered if it can give tools like this any performance gain.

https://github.com/NVlabs/FasterViT

**Comment by yurijmikhalevich** [comment]
Hi @walking-octopus, thank you for sharing the model. I'll check it out.

**Comment by yurijmikhalevich** [comment]
Integrating this model will require training a CLIP with it from scratch. This sounds like a lot of fun and should be straightforward-ish to implement if we take the `open_clip` codebase, but it is out of the closest roadmap for this repo. Closing now with the possibility of circling back to this in the future.
